FROM frolvlad/alpine-glibc

RUN apk upgrade && apk add curl

ADD ./envoy /
RUN chmod u+x /envoy

ADD ./front-envoy.yaml /etc/

ADD ./certs /etc/certs

CMD /envoy --v2-config-only -l info -c /etc/front-envoy.yaml --service-cluster front-proxy
